[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/resume"
  to = "https://resume.damato.design/donnie"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
